name: Publish to PyPI

on:
  push:
    branches:
      - '*'

jobs:
  build-package-ubuntu:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade build setuptools twine wheel flake8 pytest
          pip install --editable .

      - name: Run pytest
        run: pytest
      
      - name: Build package
        if: github.ref == 'refs/heads/main' && success()
        run: python -m build

      - name: Publish package
        if: github.ref == 'refs/heads/main' && success()
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
